apps/cms/models.py
from exts import db
from datetime import datetime
from werkzeug.security import generate_password_hash,check_password_hash


class CMSUser(db.Model):
    __tablename__='cms_user'
    id = db.Column(db.Integer,primary_key=True,autoincrement=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100),nullable=False)
    email = db.Column(db.String(50),nullable=False,unique=True)
    join_time =db.Column(db.DateTime,default=datetime.now)
    """
    想要映射到数据库里面必须添加到manage.py里面
  
    """


    def __init__(self,username,password,email):
        self.username=username
        self.password=password
        self.email=email

    @property
    def password(self):
        return self._password


    @password.setter
    def password(self,raw_password):
        self._password= generate_password_hash(raw_password)

    def check_password(self,raw_password):
        result = check_password_hash(self.password,raw_password)
        #这里也可以写为self._password(代表的是password方法下面的返回值)，其实这里的self.password指的就是这个password方法
        return result



#
# user = CMSUser()
# print(user.password)



# 密码：对外的字段名叫做password
# 密码：对内的字段名叫做_password

apps/cms/forms.py
from wtforms import StringField,IntegerField
from wtforms.validators import Email,InputRequired,Length,EqualTo
from ..forms import BaseForm


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确的邮箱格式'),InputRequired(message='请输入邮箱')])
    password = StringField(validators=[Length(6,20,message='请输入正确格式的密码')])
    remember = IntegerField()

class ResetpwdForm(BaseForm):
    oldpwd = StringField(validators=[Length(6,20,message='请输入正确格式的旧密码')])
    newpwd = StringField(validators=[Length(6,20,message='请输入正确格式的新密码')])
    newpwd2 = StringField(validators=[EqualTo("newpwd",message='确认密码必须和新密码保持一致')])

apps/forms.py
from wtforms import Form


class BaseForm(Form):
    def get_error(self):
        message = self.errors.popitem()[1][0]
        return message

app.py
from flask import Flask
from apps.cms import bp as cms_bp
from apps.front import bp as front_bp
from apps.common import bp as common_bp
import config
from exts import db
from flask_wtf import CSRFProtect




def create_app():
    app = Flask(__name__)
    app.register_blueprint(cms_bp)
    app.register_blueprint(front_bp)
    app.register_blueprint(common_bp)
    app.config.from_object(config)

    db.init_app(app)
    CSRFProtect(app)

    return app



#
# @app.route('/')
# def hello_world():
#     return 'Hello World!'


if __name__ == '__main__':
    app= create_app()
    app.run()


"""
程序流程:
(my_env) $python3 manage.py create_cms_user -u admin -p 111111 -e richard@163.com
cms用户添加成功
(my_env) $

而后直接运行此程序
"""

apps/cms/__init__.py
from .views import bp
# from .models import  CMSUser
import apps.cms.hooks

apps/cms/views.py
from flask import  Blueprint,views,render_template,request,session,redirect,url_for,g,jsonify
from  .forms import LoginForm,ResetpwdForm
from .models import CMSUser
from .decorators import login_required
import config
from exts import db
from utils import restful

bp = Blueprint("cms",__name__,url_prefix='/cms')

@bp.route('/logout/')
@login_required
def logout():
    del session[config.CMS_USER_ID]
    return redirect(url_for('cms.login'))


@bp.route('/profile/')
@login_required
def profile():
    return render_template('cms/cms_profile.html')


@bp.route('/')
@login_required
def index():
    return render_template('cms/cms_index.html')
# render_template('cms/cms_index.html')




"""
登录界面
"""


class LoginView(views.MethodView):
    def get(self,message=None):
        return render_template('cms/cms_login.html',message=message )

    def post(self):
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = CMSUser.query.filter_by(email = email).first()
            if user and user.check_password(password):
                session[config.CMS_USER_ID]=user.id
                """
            #session是存储了user_id,同时这个session又保存在cookies当中,当用户再次请求的时候会把cookies提交给服务器
                这时候falsk就会把cookies中的session拿到,而后把相应的数据解码出来
                
                """
                if remember:#如果用户有提交这个remember,那么就让这个cookies信息保存的长一点
                    #如果session.permanent = True
                    #则过期时间31天
                    session.permanent = True
                return redirect(url_for('cms.index'))
            else:
                return self.get(message="邮箱或者密码错误")

        else:
            # print(form.errors)
            # message = form.errors.popitem()[1][0]
            message = form.get_error()
            # print(message)
            # 请输入正确格式的密码

            """
            form.errors.popitem()[1]是一个列表:
         {'password': ['请输入正确格式的密码']}
         里面的第0项为:请输入正确格式的密码

            """

            return self.get(message=message)


class ResetPwdView(views.MethodView):
    decorators=[login_required]
    def get(self):
        return render_template('cms/cms_resetpwd.html')

    def post(self):
        form = ResetpwdForm(request.form)
        if form.validate():
            oldpwd = form.oldpwd.data
            newpwd = form.newpwd.data
            user = g.cms_user
            if user.check_password(oldpwd):
                user.password = newpwd
                db.session.commit()
                # return jsonify({"code": 200, "message": ""})
                return  restful.success()
            else:
                # print("post里层循环400")
                return restful.params_error("旧密码错误")
        else:
            message = form.get_error()
            # print("post外层循环400")
            return restful.params_error(message)

bp.add_url_rule('/login/',view_func=LoginView.as_view('login'))
##一定要和base.js里面的重置密码url保持一致;这里是和第31行一样
bp.add_url_rule('/resetpwd/',view_func=ResetPwdView.as_view('resetpwd'))

apps/common/__init__.py
from .views import bp

apps/common/views.py
from flask import  Blueprint

bp = Blueprint("common",__name__,url_prefix='/common')

@bp.route('/')
def index():
    return 'common  index'

apps/front/__init__.py
from .views import bp

apps/front/views.py
from flask import  Blueprint

bp = Blueprint("front",__name__)#url_prefix='cms'表示一个前缀,这里不需要

@bp.route('/')
def index():
    return 'front index'

templates/cms/cms_base.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% block title %}{% endblock %}</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/base.css')}}">
    <script src="{{ static('cms/js/base.js')}}"></script>
    <script src="{{ static("common/zlajax.js") }}"></script>
{% block head %}{% endblock %}
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ g.cms_user.username }}<span>[超级管理员]</span></a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="#">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="{{ url_for('cms.profile') }}">个人信息</a></li>
                        <li><a href="{{ url_for('cms.resetpwd') }}">修改密码</a></li>
                        <li><a href="#">修改邮箱</a></li>
                    </ul>
                </li>

                <li class="nav-group post-manage"><a href="#">帖子管理</a></li>
                <li class="comments-manage"><a href="#">评论管理</a></li>
                <li class="board-manage"><a href="#">板块管理</a></li>

                <li class="nav-group user-manage"><a href="#">用户管理</a></li>
                <li class="role-man age"><a href="#">组管理</a></li>

                <li class="nav-group cmsuser-manage"><a href="#">CMS用户管理</a></li>
                <li class="cmsrole-manage"><a href="#">CMS组管理</a></li>
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>{% block page_title %}{% endblock %}</h1>
            <div class="main_content">
                {% block main_content %}
                {% endblock %}

            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_index.html
{% extends 'cms/cms_base.html'%}
{% block title %}
    study课堂CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到study课堂CMS管理系统
{% endblock %}
{#{% block main_content %}#}
{#{% endblock %}#}

templates/cms/cms_index_backup.html
{% from "common/_macros.html" import static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>标题</title>
    <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{{ static('cms/css/base.css')}}">
    <script src="{{ static('cms/js/base.js ')}}"></script>
</head>
<body>
     <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">知了课堂论坛CMS管理系统</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">{{ g.cms_user.username }}<span>[超级管理员]</span></a></li>
            <li><a href="{{ url_for('cms.logout') }}">注销</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="查找...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
          <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav-sidebar">
                <li class="unfold"><a href="#">首页</a></li>
                <li class="profile-li">
                    <a href="#">个人中心<span></span></a>
                    <ul class="subnav">
                        <li><a href="#">个人信息</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li><a href="#">修改邮箱</a></li>
                    </ul>
                </li>

                <li class="nav-group post-manage"><a href="#">帖子管理</a></li>
                <li class="comments-manage"><a href="#">评论管理</a></li>
                <li class="board-manage"><a href="#">板块管理</a></li>

                <li class="nav-group user-manage"><a href="#">用户管理</a></li>
                <li class="role-manage"><a href="#">组管理</a></li>

                <li class="nav-group cmsuser-manage"><a href="#">CMS用户管理</a></li>
                <li class="cmsrole-manage"><a href="#">CMS组管理</a></li>
            </ul>
          </div>
          <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
            <h1>标题</h1>
            <div class="main_content">
                整体内容
            </div>
          </div>
      </div>
    </div>
</body>
</html>

templates/cms/cms_login.html
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <meta name="description" content="">
    <meta name="author" content="">
{#    <link rel="icon" href="../../favicon.ico">#}

    <title>登录论坛(sign for bbs)</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">#}

    <!-- Custom styles for this template -->
{#    <link href="signin.css" rel="stylesheet">#}
      <link href="{{ url_for('static',filename='cms/css/signin.css') }}" rel="stylesheet">

{#    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->#}
{#    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->#}
{#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}
{##}
{#    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->#}
{#    <!--[if lt IE 9]>#}
{#      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>#}
{#      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>#}
{#    <![endif]-->#}
  </head>

  <body>

    <div class="container">

      <form class="form-signin"  method= "post">
        <h2 class="form-signin-heading">请登录</h2>
          <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        <label for="inputEmail" class="sr-only">邮箱(Email address):</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="邮箱(Email address)" name="email" required autofocus>
{#          这里添加了三个name#}
        <label for="inputPassword" class="sr-only">密码(Password):</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="密码(Password)" name="password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="1" name="remember"> 记住我(Remember me)
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录:(Sign in)</button>
      </form>

{#这里是添加的#}
        {% if message %}
        <p style="text-align: center" class="text-danger">{{ message }}</p>
        {% endif %}

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>#}
  </body>
</html>

templates/cms/cms_profile.html
{% extends 'cms/cms_base.html'%}
{% block title %}
    个人信息
{% endblock %}

{% block page_title %}
{{ self.title() }}
{% endblock %}


{% block main_content %}
    {% set user = g.cms_user  %}
<table class="table table-bordered">
<tbody>

<tr>
    <td>用户名:</td>
        <td>{{  user.username }}</td>


</tr>
<tr>
    <td>邮箱:</td>
        <td>{{  user.email }}</td>


</tr>
<tr>
    <td>角色</td>
        <td>暂未实现 </td>


</tr>
<tr>
    <td>权限</td>
        <td>暂未实现</td>


</tr>
<tr>
    <td>加入时间</td>
        <td>{{  user.join_time}}</td>


</tr>
</tbody>

</table>
{% endblock %}

templates/cms/cms_resetpwd.html
{% extends 'cms/cms_base.html' %}
{% from "common/_macros.html" import static %}

{% block title -%}
    修改密码
{%- endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}
{% block head %}
    <style>
        .form-container{
            width: 300px;
        }
    </style>
    <script src="{{ static("cms/js/resetpwd.js") }}"></script>
{% endblock %}

{% block main_content%}
{#    <form action="" method ="post">#}
{#    <div  class="form-group">#}
{##}
{#        <div class="form-control">#}
{#           <span class="input-group-addon">旧密码</span>#}
{#            <input type="password" class="from-control" name="oldpwd">#}
{#        </div>#}
{##}
{##}
{#    </div>#}
{#    <div class="from-group">#}
{#         <div class="form-control">#}
{#           <span class="input-group-addon">新密码</span>#}
{#            <input type="password" class="from-control" name="newpwd">#}
{#        </div>#}
{##}
{#    </div>#}
{#    <div class="from-group">#}
{##}
{#           <div class="form-control">#}
{#           <span class="input-group-addon">确认新密码</span>#}
{#            <input type="password" class="from-control" name="newpwd2">#}
{#        </div>#}
{##}
{#    </div>#}
{#    <div class="form-group">#}
{#    <button class="btn btn-primary">立即保存</button>#}
{##}
{#    </div>#}
{#    </form>#}

      <form action="" method="post">
        <div class="form-container">
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">旧密码</span>
                    <input type="password" class="form-control" name="oldpwd" placeholder="请输入旧密码">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">新密码</span>
                    <input type="password" class="form-control" name="newpwd" placeholder="请输入新密码">
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">确认新密码</span>
                    <input type="password" class="form-control" name="newpwd2" placeholder="请输入确认密码">
                </div>
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="submit">立即保存</button>
            </div>
        </div>
    </form>
{%endblock %}

templates/common/_macros.html
{% macro static(filename) -%}
    {{ url_for("static",filename=filename) }}
{%- endmacro %}